### ISSUE TITLE
Feature request: other architectures

### ISSUE THREAD

**Issue by dpo** [julia-actions/setup-julia#101]
It would be useful to select other Julia architectures (e.g., macOS aarch64) to run on self-hosted runners. Would you be open to adding such feature to this action?

**Comment by SaschaMann** [comment]
Hi, I'm open to adding them. However, I don't have access to any self-hosted runners or aarch64 macOS hardware, which makes adding and testing archs that aren't available through GitHub's hosted runners impossible on my own.

I'm happy to accept PRs or collaborate on adding them if you have access to the required runners/hardware, though.

**Comment by dpo** [comment]
Great, thank you! Let me try to get a first version going.

**Comment by SaschaMann** [comment]
Mosè pointed out on Slack that there isn't a GHA runner for M1 yet: https://github.com/actions/runner/issues/805#issuecomment-1132966327

**Comment by SaschaMann** [comment]
These lines would need changing/additions to add support for it:

https://github.com/julia-actions/setup-julia/blob/f29cb961e8488bf333363f0f325069a721f74dee/src/installer.ts#L19-L22

https://github.com/julia-actions/setup-julia/blob/f29cb961e8488bf333363f0f325069a721f74dee/src/installer.ts#L102-L104



I might have missed something and the README would need an update too, so no guarantee for completeness.

**Comment by SaschaMann** [comment]
#102 should in theory also enable support for M1 runners, though that should be verified once those are actually available. The only thing left for that would be the addition of a new error branch when trying to install nightlies on M1 macOS, since those don't exist.

**Comment by giordano** [comment]
I successfully tested a self-hosted runner on a Macbook M1 with the new runners [`v2.292.0`](https://github.com/actions/runner/releases/tag/v2.292.0).  I used this script to test an example package:
```yaml
name: CI
on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - macOS - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: [self-hosted]
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.7.2
        arch:
          - aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Version Info
        shell: julia --color=yes {0}
        run: |
          using InteractiveUtils
          versioninfo()
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
```
