### ISSUE TITLE
Feature request: in the `arch` input, support `ARM64` as a synonym for `aarch64`

### ISSUE THREAD

**Issue by DilumAluthge** [julia-actions/setup-julia#107]
It would be really convenient for me if I could do something like the following:

```yml
- uses: julia-actions/setup-julia@v1
  with:
    version: '${{ matrix.version }}'
    arch: ${{ runner.arch }}
```

However, the [`${{ runner.arch }}`](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context) variable supports the following values: `X86`, `X64`, `ARM`, or `ARM64`.

So it would be really nice if `setup-julia` could accept `arm64` as a synonym for `aarch64`.
