### ISSUE TITLE
[Docs / Best Practices]: `ERROR: Jupyter kernel 'julia-1.9' not found.`

### ISSUE THREAD

**Issue by jdossgollin** [julia-actions/setup-julia#190]
I'm using GH Actions to compile and publish a Quarto notebook with Julia code in it and trying to figure out the best way to set up Julia for use with Quarto. When I try to follow the [Quarto / Julia docs](https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-01-basics.md), I get the following error:

```bash
ERROR: Jupyter kernel 'julia-1.9' not found.
```

To address this, I tried adding the step shown here ("Set up Julia environment.") However, this didn't fix the problem.

```yaml
...

- name: Setup Julia
  uses: julia-actions/setup-julia@v1
  with:
    version: 1.9.4

- name: Set up Julia environment
  run: julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate(); Pkg.build("IJulia")'

...
```

**What is the recommended way to set up Julia with the IJulia kernel**?

Thanks!
