### ISSUE TITLE
Unexpected ##[error]read ECONNRESET

### ISSUE THREAD

**Issue by aminya** [julia-actions/setup-julia#35]
https://github.com/timholy/SnoopCompile.jl/pull/107/checks?check_run_id=804747167

**Comment by SaschaMann** [comment]
The link to the log doesn't work properly, it sends me to the Action tab, where it doesn't show any failing jobs.

Maybe I should just wrap all the downloads in a loop that tries a few times if it fails.

**Comment by aminya** [comment]
Sorry! I guess it got removed after doing a rebase. It was a one-time thing, without any further log or messages.

**Comment by aminya** [comment]
> Maybe I should just wrap all the downloads in a loop that tries a few times if it fails.

That's a good idea!

Could you also integrate this to setup-julia? so we don't need to write in our workflows? 

```
      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts 
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
```
