### ISSUE TITLE
Set installed Julia version as output

### ISSUE THREAD

**Issue by SaschaMann** [julia-actions/setup-julia#51]
Currently the only way to determine the exact Julia version that has been installed is parsing `julia --version`. Setting the installed version as an output after it has been determined via node-semver will make it easier to use the version in subsequent steps in the workflow.

**Comment by timholy** [comment]
Is the precise commit printed for `nightly`? I took a brief scan of https://github.com/timholy/Revise.jl/pull/489/checks?check_run_id=1536730843 and couldn't see anything more specific than `julia version 1.7.0-DEV`. For nightly, it would be really handy to know the date and commit of the build to make it easier to diagnose failures.

**Comment by SaschaMann** [comment]
You can set `show-versioninfo` and it will run `InteractiveUtils.versioninfo()` which includes the commit.

```yaml
    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.version }}
        arch: ${{ matrix.arch }}
        show-versioninfo: 'true'
```

or if you only need that info for nightlies:

```yaml
    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.version }}
        arch: ${{ matrix.arch }}
        show-versioninfo: ${{ matrix.version == 'nightly' }}
```

By default it only shows the output of `julia --version` to save the time of starting Julia to display the full versioninfo.
