### ISSUE TITLE
[BUG] Run julia-actions/setup-julia@v1 Error: Could not find a Julia version that matches 1.6

### ISSUE THREAD

**Issue by vlandau** [julia-actions/setup-julia#67]
**Describe the bug**
When trying to test on 1.6 in GitHub Actions for [Omniscape.jl](https://github.com/Circuitscape/Omniscape.jl), I'm getting the following error:
```
Run julia-actions/setup-julia@v1
  with:
    version: 1.6
    arch: x64
    show-versioninfo: false
  env:
    JULIA_NUM_THREADS: 2
Error: Could not find a Julia version that matches 1.6
```

**To Reproduce**
Using this yml in the Omniscape.jl repo produced the error.

```yaml
name: CI
env:
  JULIA_NUM_THREADS: 2
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.5'
          - '1.6'
        os:
          - ubuntu-latest
          - macos-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: |
          julia --project=docs -e '
            using Documenter: doctest
            using Omniscape
            doctest(Omniscape)' 
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
```

**Expected behavior**
1.6 in the yml should point to 1.6.0-beta1
