### ISSUE TITLE
Fails with Unexpected HTTP response: 404

### ISSUE THREAD

**Issue by aminya** [julia-actions/setup-julia#8]
https://github.com/aminya/AcuteML.jl/runs/293751961
```
##[error]Unexpected HTTP response: 404
##[error]Node run failed with exit code 1
```

**Comment by SaschaMann** [comment]
Julia `1.4` doesn't have generic bianries yet, so the action can't install it. The latest version that's available is `1.3.0-rc4`.

Support for nightlies will come once #4 is merged.

---

I'll wrap it in a nicer error message that explains what's going on, though.

**Comment by islent** [comment]
Same problem here, and I've noticed the progress of https://github.com/julia-actions/setup-julia/pull/4
Just to provide some usage info. Many thanks and hope this would be solved:
```
##[error]Unexpected HTTP response: 404
##[error]Node run failed with exit code 1
```
I've tried several combinations: julia version 1.2, 1.2.0, 1.2.0-rc3; setup-julia@latest, v0.2.1, v0.2.0
None of above worked!
```yml
name: CI

on: [push, pull_request]

# 64-bit Julia only
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} #- ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.2.0-rc3'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        #arch:
        #  - x64
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v0.2.1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - run: julia -e 'println("Running test!")'
      #- uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
```
